"use client";

import { max, min } from "drizzle-orm";
import { Button } from "~/components/ui/button";
import { api } from "~/trpc/react";

// import algoliasearch from "algoliasearch/lite";
// import { Hit as AlgoliaHit } from "instantsearch.js";
// import React from "react";
// import {
//   Hits,
//   Highlight,
//   SearchBox,
//   RefinementList,
//   DynamicWidgets,
// } from "react-instantsearch";
// import { InstantSearchNext } from "react-instantsearch-nextjs";

// const client = algoliasearch("KH60NZV6Q6", "2c44fcbda3712ff9731a7d9037c95f32");

// type HitProps = {
//   hit: AlgoliaHit<{
//     width: number;
//     length: number;
//     amount: number;
//     depth: number;
//   }>;
// };

// function Hit({ hit }: HitProps) {
//   return (
//     <>
//       <Highlight hit={hit} attribute="name" className="Hit-label" />
//       <span className="Hit-price">${hit.amount}</span>
//     </>
//   );
// }

// export default function Search() {
//   return (
//     <InstantSearchNext searchClient={client} indexName="instant_search" routing>
//       <div className="Container">
//         <div>
//           <DynamicWidgets fallbackComponent={FallbackComponent} />
//         </div>
//         <div>
//           <SearchBox />
//           <Hits hitComponent={Hit} />
//         </div>
//       </div>
//     </InstantSearchNext>
//   );
// }

// function FallbackComponent({ attribute }: { attribute: string }) {
//   return (
//     <Panel header={attribute}>
//       <RefinementList attribute={attribute} />
//     </Panel>
//   );
// }

// export function Panel({
//   children,
//   header,
//   footer,
// }: {
//   children: React.ReactNode;
//   header?: React.ReactNode;
//   footer?: React.ReactNode;
// }) {
//   return (
//     <div className="ais-Panel">
//       {header && <div className="ais-Panel-header">{header}</div>}
//       <div className="ais-Panel-body">{children}</div>
//       {footer && <div className="ais-Panel-footer">{footer}</div>}
//     </div>
//   );
// }

export default function Search() {
  const createFinishedItem = api.finishedItems.create.useMutation({
    onMutate: (input) => {
      console.log("onMutate", input);
    },
    onSuccess: (data) => {
      console.log("onSuccess", data);
    },
    onError: (error) => {
      console.log("onError", error);
    },
  });

  return (
    <div>
      <h1>TODO: BUILD THIS PAGE</h1>
    </div>
  );
}

const data = [
  {
    width: 48,
    length: 40,
    depth: 24,
    description: "51BC HSC Tote",
    flute: "BC" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 51,
    itemNum: "2817 / AWPL17A",
    amount: 103,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 49,
    length: 41,
    depth: 5,
    description: "32C Lid",
    flute: "C" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 32,
    itemNum: "2818 / AWPL17A/B",
    amount: 249,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 24,
    length: 10,
    depth: 4,
    flute: "C" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 32,
    description: "32C RSC Glued S-12609",
    itemNum: "AWPL40G",
    amount: 769,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 24,
    length: 12,
    depth: 2,
    flute: "B" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 32,
    description: "32B D/C - Roll Over S-13341",
    itemNum: "AWPL40E",
    amount: 525,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 25,
    length: 17,
    depth: 31.5,
    flute: "BC" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 48,
    description: "48BC FOL Glued BOX-2410-02",
    itemNum: "AWPL20A",
    amount: 106,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 25,
    length: 2,
    depth: 10,
    flute: "C" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 32,
    description: "32C RSC Glued",
    itemNum: "AWPL50",
    amount: 101,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 26,
    length: 10,
    depth: 4,
    description: "48BC FOL Glued BOX-2510-02",
    itemNum: "AWPL20B",
    amount: 206,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 26,
    length: 12,
    depth: 4,
    flute: "C" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 32,
    description: "32C RSC Glued S-19826",
    itemNum: "AWPL40F",
    amount: 724,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 27,
    length: 2,
    depth: 10,
    flute: "BC" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 48,
    description: "48BC FOL Glued BOX-2412-04",
    itemNum: "AWPL20E",
    amount: 208,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 30,
    length: 2,
    depth: 10,
    flute: "BC" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 48,
    description: "48BC FOL Glued BOX-2710-02",
    itemNum: "AWPL20C",
    amount: 220,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 30,
    length: 2,
    depth: 10,
    flute: "BC" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 48,
    description: "48BC FOL Glued BOX-3010-02",
    itemNum: "AWPL20D",
    amount: 112,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 4,
    length: 4,
    depth: 36,
    flute: "C" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 32,
    description: "32C RSC Glued S4132",
    itemNum: "AWPL40A",
    amount: 1028,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 4,
    length: 4,
    depth: 48,
    flute: "C" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 32,
    description: "32C RSC Glued S-4465",
    itemNum: "AWPL40B",
    amount: 600,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 6,
    length: 6,
    depth: 36,
    flute: "C" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 32,
    description: "32C RSC Glued S-4135",
    itemNum: "AWPL40C",
    amount: 287,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 6,
    length: 6,
    depth: 48,
    flute: "C" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 32,
    description: "32C RSC Glued S-4381",
    itemNum: "AWPL40D",
    amount: 336,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 77,
    length: 42,
    depth: 36,
    flute: "BC" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 48,
    description: "48BC HSC Pallet Box",
    itemNum: "AWP45",
    amount: 214,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 78,
    length: 43,
    depth: 5,
    flute: "BC" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 0,
    description: "DW Tray Lid",
    itemNum: "AWP45lid",
    amount: 216,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 47.5,
    length: 9,
    depth: 29,
    flute: "C" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 44,
    description: "44 C RSC Glued BOX-OFP-5419",
    itemNum: "AWPL67",
    amount: 57,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 36.5,
    length: 14.625,
    depth: 37,
    flute: "BC" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 48,
    description: "48 DW FOL BOX-RAK-2005",
    itemNum: "AWP64B",
    amount: 13,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 30,
    length: 6,
    depth: 50,
    flute: "BC" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 48,
    description: "48 DW RSC glued",
    itemNum: "AWPL56B",
    amount: 112,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 23,
    length: 6,
    depth: 50,
    flute: "BC" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 48,
    description: "48 DW RSC glued",
    itemNum: "AWPL56A",
    amount: 227,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: "CK",
    length: 10,
    depth: 80,
    flute: "BC" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 0,
    description: "Scored Sheet",
    itemNum: "1277",
    amount: 1,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: "CK",
    length: 30,
    depth: 109,
    flute: "BC" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 0,
    description: "Scored Sheet",
    itemNum: "1276",
    amount: "good",
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: "CK",
    length: 42,
    depth: 109,
    flute: "BC" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 0,
    description: "Scored Sheet",
    itemNum: "1278",
    amount: "good",
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: "CK",
    length: 12.875,
    depth: 0,
    description: "23C Corner Protector",
    itemNum: "9",
    flute: "C" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 23,
    amount: 0,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: "CK",
    length: 21.875,
    depth: 0,
    description: "23C Corner Protector",
    itemNum: "10",
    flute: "C" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 23,
    amount: 1500,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: "CK",
    length: 24.875,
    depth: 0,
    description: "23C Corner Protector",
    itemNum: "11",
    flute: "C" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 23,
    amount: 0,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 22,
    length: 16.5,
    depth: 1.125,
    description: "Door Surround",
    itemNum: "7",
    flute: "C" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 32,
    amount: 200,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 22.125,
    length: 16.75,
    depth: 1.25,
    flute: "B" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 26,
    description: "26B Box Sleeve",
    itemNum: "8",
    amount: 200,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 0,
    length: 22.75,
    depth: 14.75,
    flute: "C" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 44,
    description: "44C Tray Formed Boxes",
    itemNum: "708",
    amount: 10500,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 40,
    length: 48,
    depth: 0,
    flute: "B" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 18,
    description: "ECT B Slip Sheet",
    itemNum: "2126/1498",
    amount: 4194,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 40,
    length: 48,
    depth: 18,
    flute: "B" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 18,
    description: "18pt Slip Sheet",
    itemNum: "0",
    amount: 12500,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 0,
    length: 4.5,
    depth: 89,
    flute: "B" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 23,
    description: "23B Tray Liner 6000854",
    itemNum: "WF1B",
    amount: 76000,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 10,
    length: 10,
    depth: 10,
    flute: "C" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 32,
    description: "Stock Box",
    itemNum: "AWPL41C",
    amount: 200,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 12,
    length: 12,
    depth: 12,
    flute: "C" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 32,
    description: "Stock Box",
    itemNum: "AWPL41D",
    amount: 350,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 14,
    length: 14,
    depth: 14,
    flute: "C" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 32,
    description: "Stock Box",
    itemNum: "AWPL41E",
    amount: 225,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 16,
    length: 16,
    depth: 16,
    flute: "C" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 32,
    description: "Stock Box",
    itemNum: "AWPL41F",
    amount: 250,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 18,
    length: 18,
    depth: 18,
    flute: "C" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 32,
    description: "Stock Box",
    itemNum: "AWPL41G",
    amount: 250,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 24,
    length: 0,
    depth: 0,
    flute: "C" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 32,
    description: "Kraft Paper",
    itemNum: "2884",
    amount: 4,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 36,
    length: 0,
    depth: 0,
    flute: "C" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 32,
    description: "Kraft Paper",
    itemNum: "2885",
    amount: 8,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 48,
    length: 0,
    depth: 0,
    flute: "C" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 32,
    description: "Kraft Paper",
    itemNum: "2856",
    amount: 8,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
  {
    width: 48,
    length: 24,
    depth: 24,
    flute: "C" as "B" | "C" | "E" | "F" | "BC" | "pt",
    color: "kraft" as "kraft" | "white",
    strength: 32,
    description: "32C RSC Produce Sham Carton",
    itemNum: "AWPL41B",
    amount: 100,
    amountPerPallet: 1,
    inventoryThreshold: 0,
    maxInventoryThreshold: 0,
    prodAmount: 0,
  },
];
